=== KatyaS91/TATJAVA01_2017_Task05_Katsiaryna_Skarzhynskaya/src/main/java/com/epam/task5/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/menu"
        xmlns:tns="http://www.example.org/menu" elementFormDefault="qualified">
    <element name="menu">
        <complexType>
            <sequence>
                <element name="course" type="tns:Course" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Course">
        <sequence>
            <element name="dish" type="tns:Dish" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id">
            <simpleType>
                <restriction base="string">
                    <enumeration value="appetizer"/>
                    <enumeration value="main"/>
                    <enumeration value="breakfast"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="Dish">
        <sequence>
            <element name="name" type="string"/>
            <element name="description" type="string"/>
            <element name="weight" type="string">
            </element>
            <element name="price" type="nonNegativeInteger" default="0"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>
</schema>

=== KatyaS91/TATJAVA01_2017_Task05_Katsiaryna_Skarzhynskaya/src/main/java/com/epam/task5/menu.xml
<?xml version="1.0" encoding="UTF-8" ?>
<menu xmlns="http://www.example.org/menu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.example.org/menu menu.xsd">
    <course id="appetizer">
        <dish id="A1">
            <name>Брынза</name>
            <description>Рассольный сыр</description>
            <weight>75</weight>
            <price>10</price>
        </dish>
    </course>
    <course id="main">
        <dish id="B1">
            <name>Жульен</name>
            <description>С курицей</description>
            <weight>120</weight>
            <price>145</price>
        </dish>
    </course>
    <course id="breakfast">
        <dish id="C1">
            <name>Омлет</name>
            <description>2 яйца</description>
            <weight>100</weight>
            <price>56</price>
        </dish>
    </course>
</menu>
